var wordsModule = (function(){
    var words = [
        // Marcel Proust, In Search of Lost Time
        "We believe that we can change the things around us in accordance with our desires—we believe it because otherwise we can see no favourable outcome. We do not think of the outcome which generally comes to pass and is also favourable: we do not succeed in changing things in accordance with our desires, but gradually our desires change. The situation that we hoped to change because it was intolerable becomes unimportant to us. We have failed to surmount the obstacle, as we were absolutely determined to do, but life has taken us round it, led us beyond it, and then if we turn round to gaze into the distance of the past, we can barely see it, so imperceptible has it become.",
        
        //http://www.popsci.com/lunar-xprize-google-moon-landing
        "If you can send a spacecraft to the moon and loop around our natural satellite one time, or—even better—gently set a rover down on the lunar surface, there could be money in it for you. $4.75 million, to be precise.| That is, if you happen to be one of the select few finalist teams competing for the Google Lunar XPrize. The awarding organizations—Xprize and Google—have decided to split two prize amounts between whatever teams manage to achieve two distinct feats:| $1.75 million is up for grabs as part of the Lunar Arrival Milestone Prize. To get a slice of that pie, a “spacecraft must complete one orbit around the moon or enter a direct descent approach to the lunar surface,” according to press materials supplied by XPrize.| A larger chunk—three million dollars—will be split between spacecraft that win the Soft Landing Milestone Prize. To win that, the awarding foundation says that a “spacecraft must transmit data proving it soft-landed on the lunar surface.| Both of those achievements must be met before March 31, 2018, which is also the new deadline by which teams must complete their attempt at the $30 million Grand Prize. The Grand Prize goes to the first team that manages to put a robot on the moon, explore for 500 meters, and send high-def images and video back to Earth. There will also be a smaller prize for the second team to meet those goals. The catch? The teams need to be 90 percent privately funded.| Robotic exploration of our solar system has long been the purview of national space agencies, which spend millions, and sometimes billions of dollars on developing new technologies. The Curiosity Rover, for example, cost about $2.6 billion (not a lot when you consider the length of the mission, but still pretty expensive). This competition is an attempt to find cheaper ways of exploring the space around us. Previous privately funded missions, like 4M back in 2014, have been relatively simple in design—and none have landed on the lunar surface.| Five teams so far have secured contracts to launch their spacecraft; SpaceIL, Moon Express, Synergy Moon, TeamIndus, and HAKUTO. They all have official plans to launch something by the end of 2017, which is going to make for an exciting next few months in space news, but they now have a few extra months to complete their mission.| It’s a sweet prize, but getting a share of the money won’t be easy. After all, it actually is rocket science.",
        
        //Toni Morrison, Song of Solomon
        "You think because he doesn’t love you that you are worthless. You think that because he doesn’t want you anymore that he is right — that his judgement and opinion of you are correct. If he throws you out, then you are garbage. You think he belongs to you because you want to belong to him. Don’t. It’s a bad word, ‘belong.’ Especially when you put it with somebody you love. Love shouldn’t be like that. Did you ever see the way the clouds love a mountain? They circle all around it; sometimes you can’t even see the mountain for the clouds. But you know what? You go up top and what do you see? His head. The clouds never cover the head. His head pokes through, beacuse the clouds let him; they don’t wrap him up. They let him keep his head up high, free, with nothing to hide him or bind him. You can’t own a human being. You can’t lose what you don’t own. Suppose you did own him. Could you really love somebody who was absolutely nobody without you? You really want somebody like that? Somebody who falls apart when you walk out the door? You don’t, do you? And neither does he. You’re turning over your whole life to him. Your whole life, girl. And if it means so little to you that you can just give it away, hand it to him, then why should it mean any more to him? He can’t value you more than you value yourself.",
        
        //Haruki Murakami, Kafka On The Shore
        "Sometimes fate is like a small sandstorm that keeps changing directions. You change direction but the sandstorm chases you. You turn again, but the storm adjusts. Over and over you play this out, like some ominous dance with death just before dawn. Why? Because this storm isn’t something that blew in from far away, something that has nothing to do with you. This storm is you. Something inside of you. So all you can do is give in to it, step right inside the storm, closing your eyes and plugging up your ears so the sand doesn’t get in, and walk through it, step by step. There’s no sun there, no moon, no direction, no sense of time. Just fine white sand swirling up into the sky like pulverized bones. That’s the kind of sandstorm you need to imagine."
    ];

    return{
        getWords(textNumber){
            return words[textNumber];
        }
    }
})();